enable-magisk-update = true

patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "RVX-anddea"

[YouTube]
build-mode = "both"
included-patches = "'Custom branding icon for YouTube' 'MaterialYou'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

[Music]
build-mode = "both"
excluded-patches = "'Enable Cairo splash animation'"
included-patches = "'Custom branding icon for YouTube Music' 'Custom header for YouTube Music'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
